version: 2
updates:
  # - package-ecosystem: pip
  #   directory: "/.github/workflows"
  #   schedule:
  #     interval: daily
  #     time: "11:35"
  #     timezone: "America/Mexico_City"
  #   reviewers:
  #     - "edgarrmondragon"
  #   labels:
  #     - "dependencies"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/evidence"
    schedule:
      interval: daily
      time: "11:35"
      timezone: "America/Mexico_City"
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
      - "Test/ELTP"
