# Specify the workspace image configuration
image:
  file: .gitpod/Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: services
    init: |
      docker-compose -f .gitpod/docker-compose.yml up -d
      gp await-port 5432
    command: |
      docker-compose -f .gitpod/docker-compose.yml up
  - name: meltano setup
    env:
      PIP_USER: false
    init: |
      export PIP_USER=false
      cd meltano
      python3 -m venv .venv
      source .venv/bin/activate
      mkdir .meltano
      pip install meltano
      meltano install
    command: |
      cd meltano
      source .venv/bin/activate
