version: 1
default_environment: prod
project_id: b77cad0a-ffd8-494e-9e6b-18d6eacb71d4
env:
  SINGER_SDK_LOG_CONFIG: logging/singer_logging.yaml
ff:
  plugin_locks_required: true
cli:
  log_config: logging/${MELTANO_ENVIRONMENT}.yaml
plugins:
  extractors:
  - name: tap-getpocket
    variant: edgarrmondragon
    pip_url: git+https://github.com/edgarrmondragon/tap-getpocket.git python-json-logger
  - name: tap-stackexchange
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-stackexchange.git python-json-logger
    config:
      tags:
      - meltano
    select:
    - questions.*
  - name: tap-readthedocs
    variant: edgarrmondragon
    pip_url: tap-readthedocs==0.3.0 python-json-logger
    select:
    - projects.*
  - name: tap-github
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-github.git@v1.3.0 python-json-logger
    config:
      repositories:
      - edgarrmondragon/citric
      - edgarrmondragon/tap-readthedocs
    select:
    - repositories.*
    - stargazers.*
  - name: tap-pypistats
    namespace: tap_pypistats
    variant: edgarrmondragon
    pip_url: tap-pypistats==0.0.1a3 python-json-logger
    settings_group_validation:
    - [packages]
    settings:
    - kind: array
      label: Packages
      name: packages
    config:
      packages:
      - meltano
      - singer-sdk
      - singer-python
      - target-hotglue
      - pipelinewise-singer-python
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl==0.1.4
  - name: target-duckdb
    variant: jwills
    pip_url: git+https://github.com/jwills/target-duckdb.git@main duckdb==0.9.2
    config:
      path: $DUCKDB_PATH
      default_target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA
  transformers:
  - name: dbt-duckdb
    variant: jwills
    pip_url: dbt-core~=1.7.0 dbt-duckdb~=1.7.0 duckdb==0.9.2
    config:
      path: $DUCKDB_PATH
  utilities:
  - name: sqlfluff
    variant: sqlfluff
    pip_url: dbt-core~=1.7.0 dbt-duckdb~=1.7.0 sqlfluff>=3.0.0a3 sqlfluff-templater-dbt>=3.0.0a3 duckdb==0.9.2
    settings:
    - name: path
      env: DBT_DUCKDB_PATH
    config:
      path: $DUCKDB_PATH
  - name: evidence
    variant: meltanolabs
    pip_url: evidence-ext>=0.5
    config:
      home_dir: $MELTANO_PROJECT_ROOT/evidence
      settings:
        database: duckdb
        duckdb:
          filename: $DUCKDB_PATH
environments:
- name: dev
  config:
    plugins:
      loaders:
      - name: target-bigquery
        config:
          batch_size_rows: 100
- name: staging
- name: prod
  config:
    plugins:
      loaders:
      - name: target-bigquery
        config:
          batch_size_rows: 10000
  env:
    MELTANO_FF_PLUGIN_LOCKS_REQUIRED: 'true'
    MELTANO_FF_STRICT_ENV_VAR_MODE: 'true'
jobs:
- name: pocket-to-duckdb
  tasks:
  - tap-getpocket target-duckdb
- name: stackoverflow-to-duckdb
  tasks:
  - tap-stackexchange target-duckdb
- name: rtd-to-duckdb
  tasks:
  - tap-readthedocs target-duckdb
- name: gh-to-duckdb
  tasks:
  - tap-github target-duckdb
- name: pypistats-to-duckdb
  tasks:
  - tap-pypistats target-duckdb
schedules:
- name: daily_pocket
  interval: 0 12 * * *
  job: pocket-to-duckdb
- name: daily_stackoverflow
  interval: 0 12 * * *
  job: stackoverflow-to-duckdb
- name: daily_readthedocs
  interval: 0 12 * * *
  job: rtd-to-duckdb
- name: daily_github
  interval: 0 12 * * *
  job: gh-to-duckdb
- name: daily_pypistats
  interval: 0 12 * * *
  job: pypistats-to-duckdb
