version: 1
default_environment: prod
project_id: b77cad0a-ffd8-494e-9e6b-18d6eacb71d4
send_anonymous_usage_stats: false
cli:
  log_config: logging/ci.yaml
env:
  SINGER_SDK_LOG_CONFIG: logging/singer_logging.yaml
plugins:
  extractors:
  - name: tap-getpocket
    variant: edgarrmondragon
    pip_url: git+https://github.com/edgarrmondragon/tap-getpocket.git
  - name: tap-stackexchange
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-stackexchange.git
    config:
      tags:
      - meltano
    select:
    - questions.*
  - name: tap-readthedocs
    variant: edgarrmondragon
    pip_url: git+https://github.com/edgarrmondragon/tap-readthedocs.git
    select:
    - projects.*
  - name: tap-github
    variant: meltanolabs
    pip_url: https://api.github.com/repos/meltanolabs/tap-github/zipball/pull/193/head
    config:
      repositories:
      - edgarrmondragon/citric
      - edgarrmondragon/tap-readthedocs
    select:
    - repositories.*
    - stargazers.*
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
    target_schema: ''
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.4
    config:
      filepath: $MELTANO_PROJECT_ROOT/evidence/$MELTANO_ENVIRONMENT.duckdb
      default_target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA
    target_schema: $MELTANO_LOAD_DEFAULT_TARGET_SCHEMA
  transformers:
  - name: dbt-duckdb
    variant: jwills
    pip_url: dbt-core~=1.5.0 dbt-duckdb~=1.5.0
    config:
      path: $MELTANO_PROJECT_ROOT/evidence/$MELTANO_ENVIRONMENT.duckdb
  utilities:
  - name: sqlfluff
    variant: sqlfluff
    pip_url: dbt-core~=1.5.0 dbt-duckdb~=1.5.0 sqlfluff>=2.1.0 sqlfluff-templater-dbt>=2.1.0
    settings:
    - name: keyfile
      env_aliases:
      - DBT_BIGQUERY_KEYFILE
    - name: project_id
      env_aliases:
      - DBT_BIGQUERY_PROJECT_ID
    - name: dataset_id
      env_aliases:
      - DBT_BIGQUERY_DATASET_ID
    - name: location
      env_aliases:
      - DBT_BIGQUERY_LOCATION
    config:
      project_id: $BQ_PROJECT_ID
      dataset_id: ${MELTANO_ENVIRONMENT}
      keyfile: ${MELTANO_PROJECT_ROOT}/.secrets/credentials.json
      location: $BQ_LOCATION
  - name: evidence
    variant: meltanolabs
    pip_url: evidence-ext>=0.5
    config:
      home_dir: $MELTANO_PROJECT_ROOT/evidence
      settings:
        database: duckdb
        duckdb:
          filename: $MELTANO_ENVIRONMENT.duckdb
environments:
- name: dev
  config:
    plugins:
      loaders:
      - name: target-bigquery
        config:
          batch_size_rows: 100
- name: staging
- name: prod
  config:
    plugins:
      loaders:
      - name: target-bigquery
        config:
          batch_size_rows: 10000
  env:
    MELTANO_FF_PLUGIN_LOCKS_REQUIRED: 'true'
    MELTANO_FF_STRICT_ENV_VAR_MODE: 'true'
jobs:
- name: pocket-to-bq
  tasks:
  - tap-getpocket target-bigquery
- name: pocket-to-duckdb
  tasks:
  - tap-getpocket target-duckdb
- name: stackoverflow-to-bq
  tasks:
  - tap-stackexchange target-bigquery
- name: stackoverflow-to-duckdb
  tasks:
  - tap-stackexchange target-duckdb
- name: rtd-to-bq
  tasks:
  - tap-readthedocs target-bigquery
- name: rtd-to-duckdb
  tasks:
  - tap-readthedocs target-duckdb
- name: gh-to-bq
  tasks:
  - tap-github target-bigquery
- name: gh-to-duckdb
  tasks:
  - tap-github target-duckdb
schedules:
- name: daily_pocket
  interval: 0 12 * * *
  job: pocket-to-duckdb
- name: daily_stackoverflow
  interval: 0 12 * * *
  job: stackoverflow-to-duckdb
- name: daily_readthedocs
  interval: 0 12 * * *
  job: rtd-to-duckdb
- name: daily_github
  interval: 0 12 * * *
  job: gh-to-duckdb
