default_environment: dev
project_id: b77cad0a-ffd8-494e-9e6b-18d6eacb71d4
project_readonly: true
requires_meltano: '>=4.0.0rc1'
python: python3.14
venv:
  backend: uv
ff:
  plugin_locks_required: true
plugins:
  extractors:
  - name: tap-getpocket
    variant: edgarrmondragon
    pip_url: -r $MELTANO_PROJECT_ROOT/plugins/requirements/requirements.tap-getpocket.txt
  - name: tap-stackexchange
    variant: meltanolabs
    pip_url: -r $MELTANO_PROJECT_ROOT/plugins/requirements/requirements.tap-stackexchange.txt
    config:
      tags:
      - meltano
    select:
    - questions.*
  - name: tap-readthedocs
    variant: edgarrmondragon
    pip_url: -r $MELTANO_PROJECT_ROOT/plugins/requirements/requirements.tap-readthedocs.txt
    select:
    - projects.*
  - name: tap-github
    variant: meltanolabs
    pip_url: -r $MELTANO_PROJECT_ROOT/plugins/requirements/requirements.tap-github.txt
    config:
      repositories:
      - edgarrmondragon/citric
      - edgarrmondragon/tap-readthedocs
      - edgarrmondragon/tap-clinicaltrials
      - edgarrmondragon/pep610
      start_date: 1 month ago
      user_agent: $MELTANO_USER_AGENT
    select:
    - repositories.*
    - stargazers.*
  - name: tap-pypistats
    variant: edgarrmondragon
    pip_url: -r $MELTANO_PROJECT_ROOT/plugins/requirements/requirements.tap-pypistats.txt
    config:
      packages:
      - meltano
      - singer-sdk
      - singer-python
      - target-hotglue
      - pipelinewise-singer-python
      - dlt
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: -r $MELTANO_PROJECT_ROOT/plugins/requirements/requirements.target-jsonl.txt
  - name: target-duckdb
    variant: jwills
    pip_url: -r $MELTANO_PROJECT_ROOT/plugins/requirements/requirements.target-duckdb.txt
    config:
      path: $DUCKDB_PATH
      default_target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA
  utilities:
  - name: dbt-duckdb
    variant: jwills
    pip_url: -r $MELTANO_PROJECT_ROOT/plugins/requirements/requirements.dbt-duckdb.txt
    python: '3.13'
    config:
      path: $DUCKDB_PATH
  - name: sqlfluff
    variant: sqlfluff
    pip_url: -r $MELTANO_PROJECT_ROOT/plugins/requirements/requirements.sqlfluff.txt
    python: '3.13'
    settings:
    - name: path
      env: DBT_DUCKDB_PATH
    config:
      path: $DUCKDB_PATH
  - name: evidence
    variant: meltanolabs
    pip_url: evidence-ext>=0.5
    config:
      home_dir: $MELTANO_PROJECT_ROOT/evidence
      settings:
        database: duckdb
        duckdb:
          filename: $DUCKDB_PATH
environments:
- name: dev
- name: staging
- name: prod
  env:
    MELTANO_FF_PLUGIN_LOCKS_REQUIRED: 'true'
    MELTANO_FF_STRICT_ENV_VAR_MODE: 'true'
jobs:
- name: pocket-to-duckdb
  tasks:
  - tap-getpocket target-duckdb
- name: stackoverflow-to-duckdb
  tasks:
  - tap-stackexchange target-duckdb
- name: rtd-to-duckdb
  tasks:
  - tap-readthedocs target-duckdb
- name: gh-to-duckdb
  tasks:
  - tap-github target-duckdb
- name: pypistats-to-duckdb
  tasks:
  - tap-pypistats target-duckdb
