version: 1
default_environment: dev
project_id: b77cad0a-ffd8-494e-9e6b-18d6eacb71d4
project_readonly: true
python: python3.13
cli:
  log_config: logging/dev.yaml
venv:
  backend: uv
ff:
  plugin_locks_required: true
env:
  SINGER_SDK_LOG_CONFIG: logging/singer_logging.yaml
  UV_EXCLUDE_NEWER: 2025-03-31
plugins:
  extractors:
  - name: tap-getpocket
    variant: edgarrmondragon
    pip_url: git+https://github.com/edgarrmondragon/tap-getpocket.git@dfa5519a6fdf6dfc9dee4fcc604c796a85984072 python-json-logger
  - name: tap-stackexchange
    variant: meltanolabs
    pip_url: tap-stackexchange==0.0.4 python-json-logger
    config:
      tags:
      - meltano
    select:
    - questions.*
  - name: tap-readthedocs
    variant: edgarrmondragon
    pip_url: tap-readthedocs==0.5.7 python-json-logger
    select:
    - projects.*
  - name: tap-github
    variant: meltanolabs
    pip_url: meltanolabs-tap-github==1.16.2 python-json-logger
    config:
      repositories:
      - edgarrmondragon/citric
      - edgarrmondragon/tap-readthedocs
      - edgarrmondragon/tap-clinicaltrials
      - edgarrmondragon/pep610
      start_date: 1 month ago
      user_agent: $MELTANO_USER_AGENT
    select:
    - repositories.*
    - stargazers.*
  - name: tap-pypistats
    namespace: tap_pypistats
    variant: edgarrmondragon
    pip_url: tap-pypistats[pinned]==0.0.8 python-json-logger
    settings_group_validation:
    - - packages
    settings:
    - kind: array
      label: Packages
      name: packages
    config:
      packages:
      - meltano
      - singer-sdk
      - singer-python
      - target-hotglue
      - pipelinewise-singer-python
      - dlt
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl==0.1.4
  - name: target-duckdb
    variant: jwills
    pip_url: duckdb==1.2.1 target-duckdb==0.8.0
    config:
      path: $DUCKDB_PATH
      default_target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA
  utilities:
  - name: dbt-duckdb
    variant: jwills
    pip_url: dbt-core~=1.10.0b1 dbt-duckdb~=1.9.1 duckdb==1.2.1 meltano-dbt-ext~=0.3.0
    config:
      path: $DUCKDB_PATH
  - name: sqlfluff
    variant: sqlfluff
    pip_url: dbt-core~=1.10.0b1 dbt-duckdb~=1.9.1 sqlfluff~=3.3 sqlfluff-templater-dbt~=3.3 duckdb==1.2.1
    settings:
    - name: path
      env: DBT_DUCKDB_PATH
    config:
      path: $DUCKDB_PATH
  - name: evidence
    variant: meltanolabs
    pip_url: evidence-ext>=0.5
    config:
      home_dir: $MELTANO_PROJECT_ROOT/evidence
      settings:
        database: duckdb
        duckdb:
          filename: $DUCKDB_PATH
environments:
- name: dev
- name: staging
- name: prod
  env:
    MELTANO_FF_PLUGIN_LOCKS_REQUIRED: 'true'
    MELTANO_FF_STRICT_ENV_VAR_MODE: 'true'
jobs:
- name: pocket-to-duckdb
  tasks:
  - tap-getpocket target-duckdb
- name: stackoverflow-to-duckdb
  tasks:
  - tap-stackexchange target-duckdb
- name: rtd-to-duckdb
  tasks:
  - tap-readthedocs target-duckdb
- name: gh-to-duckdb
  tasks:
  - tap-github target-duckdb
- name: pypistats-to-duckdb
  tasks:
  - tap-pypistats target-duckdb
