version: 1
disable_existing_loggers: no

formatters:
  structured_colored:
    (): meltano.core.logging.console_log_formatter
    colors: True
    show_locals: True
  json:
    (): meltano.core.logging.json_formatter
    # include_callsite_parameters: True
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured_colored
    stream: "ext://sys.stderr"
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: logs/meltano.log
    formatter: json
  http:
    class: logging.FileHandler
    level: DEBUG
    filename: logs/http.log
    formatter: json
root:
  level: DEBUG
  handlers: [console, file]
loggers:
  urllib3:
    level: DEBUG
    propagate: yes
    handlers: [http]
  # Disable logging of tap and target stdout
  meltano.core.block.extract_load:
    handlers: [file]
    level: INFO
    propagate: no
