version: 1
disable_existing_loggers: no

formatters:
  structured:
    (): meltano.core.logging.console_log_formatter
    colors: false
  json:
    (): meltano.core.logging.json_formatter
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: structured
    stream: "ext://sys.stderr"
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: logs/meltano.log
    formatter: json
root:
  level: DEBUG
  handlers: [file, console]
loggers:
  # Disable logging of tap and target stdout
  meltano.core.block.extract_load:
    handlers: [file]
    level: INFO
    propagate: no
