version: 1
disable_existing_loggers: no

formatters:
  structured:
    (): meltano.core.logging.console_log_formatter
    colors: true
  json:
    (): meltano.core.logging.json_formatter
    callsite_parameters: false
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured
    stream: "ext://sys.stderr"
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: logs/meltano.log
    formatter: json
root:
  handlers: [console]
loggers:
  meltano:
    level: DEBUG
  meltano.cli:
    level: INFO
  meltano.core:
    level: INFO
  meltano.plugin.stderr:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  meltano.plugin.stdout:
    level: WARNING
  meltano.core.plugin.singer.catalog:
    level: INFO
