name: pkl

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pkl:
    name: Check stale pkl output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install pkl
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: 0.25.2

      - name: Check stale pkl output
        run: pkl eval pkl/main.pkl --format=yaml > meltano.yml

      - name: Check if meltano.yml is different
        run: git diff --exit-code meltano.yml
